### ISSUE TITLE
Missing #include <memory> in main.cpp

### ISSUE THREAD

**Issue by sgemme-csa** [asplang/asp#1]
Compile error: 

```
[ 93%] Building CXX object standalone/CMakeFiles/asps.dir/main.cpp.o
/opt/software/asp/standalone/main.cpp: In function 'int main(int, char**)':
/opt/software/asp/standalone/main.cpp:350:17: error: 'unique_ptr' was not declared in this scope
  350 |     auto code = unique_ptr<char[]>();
      |                 ^~~~~~~~~~
/opt/software/asp/standalone/main.cpp:21:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   20 | #include <climits>
  +++ |+#include <memory>
   21 | 
/opt/software/asp/standalone/main.cpp:350:28: error: expected primary-expression before 'char'
  350 |     auto code = unique_ptr<char[]>();
      |                            ^~~~
/opt/software/asp/standalone/main.cpp:361:28: error: expected primary-expression before 'char'
  361 |     auto data = unique_ptr<char[]>(new (nothrow) char[dataByteSize]);
      |                            ^~~~
/opt/software/asp/standalone/main.cpp:390:36: error: expected primary-expression before 'char'
  390 |     auto externalCode = unique_ptr<char[]>();
      |                                    ^~~~
```
Adding ```#include <memory>``` fixes the problem.
I am using gcc 13.x

**Comment by allenbtaylor** [comment]
Yes, according to the standard, `unique_ptr` is defined in `<memory>`. I just released 1.2.3.3 to fix a regression, so I'll included this fix in the next release. Thanks!

**Comment by allenbtaylor** [comment]
My Linux build machine uses gcc v11.4 and built fine, but I was able to build on a Linux that has gcc v13.3 and saw the issues there. The fix was committed and is now available in Asp release 1.2.3.4.
